##############################################
# Example TOML file for cxAMQP
##############################################

[cxAMQP]
# All servers follow a FQDN convention with injectable host name replacable by {host}
defaultUrl = 'amqp://user:password@{host}.domain.com'
# Array of hosts
hosts = ['host1', 'host2', 'host3']

# List all the queues which we will pull from on all hosts
[cxAMQP.queue]
pull = ['test']

# Bindings
[[cxAMQP.bindings]]
exchange = "amq.topic"
queue = "test-topic"
topic = ["test-topic"]

[[cxAMQP.bindings]]
exchange = "amq.headers"
queue = "test-headers"
headers = {hello = "world"}